name: HARDN - Security Automation Workflow

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 03:00 UTC

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.10"
        activate-environment: hardn
        environment-file: environment.yml
        auto-activate-base: false

    - name: Install Dependencies
      shell: bash -l {0}
      run: |
        conda activate hardn
        conda install --file requirements.txt
        pip install -r requirements-dev.txt

    - name: Run Security Checks
      shell: bash -l {0}
      run: |
        conda activate hardn
        bandit -r hardn
        safety check

    - name: Run Unit Tests
      shell: bash -l {0}
      run: |
        conda activate hardn
        pytest --cov=hardn --cov-report=xml

    - name: Upload Test Coverage Report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml

    - name: Package and Build
      shell: bash -l {0}
      run: |
        conda activate hardn
        python setup.py sdist bdist_wheel

    - name: Publish to PyPI (on release)
      if: startsWith(github.ref, 'refs/tags/v')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

    - name: Create Release Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: HARDN-Build
        path: dist/
